-- Generated by ics_to_sql.py
-- 13 customer(s), 13 appointment(s)

-- CUSTOMERS (upsert by phone — preserves existing records)
INSERT INTO customers (id, name, phone) VALUES ('0da5405f-2f80-55ab-9c0b-31dfdc72ecd8', 'Lucas Oliveira', '9991590519') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('aade652b-32f2-5dda-8478-13033b47b83a', 'João Pedro', '6792742961') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('13d6c870-139d-51bb-9e3b-59ae13a55b5d', 'Guilherme Pinheiro', '6796025704') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('4c78ec23-4927-57a6-a30b-1cc011cac0d5', 'Erik Artioli', '6784658461') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('b629535d-74c1-57ca-92b3-fed1a4948043', 'Francesco', '6781035063') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('5b1c7896-7d3e-5cee-92a7-d0ad35aca43b', 'Jonatha', '6798455935') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('631732b6-6ea8-5c6c-a3b7-3908f9610738', 'Adenilson', '6793040046') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('c9161721-cbed-56dc-93cf-a506aee2d254', 'Arildo Benites', '6791099109') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('e5bf1edc-0303-596b-ba74-7ffb30b5035e', 'Raquel Duran', '17996612310') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('54624083-ed0a-52e3-9361-14ce2c7931f2', 'Rodrigo carioca', '21971789126') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('08c62eb6-a359-5490-b01b-90252c44ff00', 'Thiago Fretez', '6784099899') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('13def6bf-f6a0-5c00-8219-9401b7ed0a28', 'Ricardo', '6792303674') ON CONFLICT (phone) DO NOTHING;
INSERT INTO customers (id, name, phone) VALUES ('3ff27b64-f228-5044-8f71-3eeed5c0b355', 'André Luiz Widal', '6796339555') ON CONFLICT (phone) DO NOTHING;

-- APPOINTMENTS
-- Lucas Oliveira
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', 'bd44b608-24f5-45f4-a8f4-2db93e8399ac', '0da5405f-2f80-55ab-9c0b-31dfdc72ecd8', '2026-04-01', '10:00', '10:30', 8000, 'completed', '085b04fc25e6a70e1cec4d75e1a3763d96c15b0fa4bb9ab8ebf62ae5043a13b7');

-- João Pedro
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', '9ad35d39-d3dd-49b2-ba9d-43012e11b8c8', 'aade652b-32f2-5dda-8478-13033b47b83a', '2026-04-01', '16:00', '16:30', 5000, 'completed', '21ede067007d35f5218d36720f1ad4d3cfc4f1728b2930cff3012365bd0ac8ee');

-- Guilherme Pinheiro
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', '9ad35d39-d3dd-49b2-ba9d-43012e11b8c8', '13d6c870-139d-51bb-9e3b-59ae13a55b5d', '2026-04-01', '11:00', '11:30', 5000, 'completed', '7cd05a602d2003a98b434b049e5f6d9eb57e7556b5b4c4a602df5ddc4ef1c6b2');

-- Erik Artioli
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', 'bd44b608-24f5-45f4-a8f4-2db93e8399ac', '4c78ec23-4927-57a6-a30b-1cc011cac0d5', '2026-04-01', '09:00', '09:30', 8000, 'completed', '3891d0b2d5d3071b2694288379787fc3fc4cd1ebff618f95a584852bdbed98bc');

-- Francesco
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', '9ad35d39-d3dd-49b2-ba9d-43012e11b8c8', 'b629535d-74c1-57ca-92b3-fed1a4948043', '2026-04-01', '08:30', '09:00', 5000, 'completed', '1d082c2f0c9ff90a167b09dbddefbfdce1d1dfb34d90de4b60e814b8fb298c9c');

-- Jonatha
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', '9ad35d39-d3dd-49b2-ba9d-43012e11b8c8', '5b1c7896-7d3e-5cee-92a7-d0ad35aca43b', '2026-04-01', '18:00', '18:30', 5000, 'completed', 'ac4eb19848c00a74d9ebbeaba72214ac561da244b61a209f2d077cd2fb147bcd');

-- Adenilson
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', '9ad35d39-d3dd-49b2-ba9d-43012e11b8c8', '631732b6-6ea8-5c6c-a3b7-3908f9610738', '2026-04-01', '18:30', '19:00', 5000, 'completed', '53d8df8bd5e99b9d7c34cf4d9e5708b96cb34b35d9785142bcbd0246963949bf');

-- Arildo Benites
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', 'bd44b608-24f5-45f4-a8f4-2db93e8399ac', 'c9161721-cbed-56dc-93cf-a506aee2d254', '2026-04-01', '14:00', '14:30', 8000, 'completed', '094da931e2708f5123d3eb5d4725b79aaa6edf065f28259da83567f12523d00e');

-- Raquel Duran
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', '9ad35d39-d3dd-49b2-ba9d-43012e11b8c8', 'e5bf1edc-0303-596b-ba74-7ffb30b5035e', '2026-04-01', '16:30', '17:00', 5000, 'completed', '14d7a06c71d981760c92ad2378e318b0fbc205ed0191d64518a595c247b688d9');

-- Rodrigo carioca
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', '9ad35d39-d3dd-49b2-ba9d-43012e11b8c8', '54624083-ed0a-52e3-9361-14ce2c7931f2', '2026-04-01', '10:30', '11:00', 5000, 'completed', 'ca4d0de6fe42c25f7a3130b4095fa0d1ab6f98375e1f2a0f67f19b5321c6c2fe');

-- Thiago Fretez
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', 'bd44b608-24f5-45f4-a8f4-2db93e8399ac', '08c62eb6-a359-5490-b01b-90252c44ff00', '2026-04-01', '17:00', '17:30', 8000, 'completed', '1e267bfdfe20fa958277b6b4091665036d8d0b455430a9973d9fba48bb2ec09f');

-- Ricardo
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', '9ad35d39-d3dd-49b2-ba9d-43012e11b8c8', '13def6bf-f6a0-5c00-8219-9401b7ed0a28', '2026-04-01', '17:30', '18:00', 5000, 'completed', 'd127507e4f3e5ab784f8e1e6cb31cf36c1eca4fce0e63674f5452edfe24aebb2');

-- André Luiz Widal
INSERT INTO appointments (id, barber_id, service_id, customer_id, date, start_time, end_time, price_cents, status, cancel_token) VALUES (gen_random_uuid(), '74176d72-39ac-423d-8464-e9de7f1b1848', 'bd44b608-24f5-45f4-a8f4-2db93e8399ac', '3ff27b64-f228-5044-8f71-3eeed5c0b355', '2026-04-01', '11:30', '12:00', 8000, 'completed', '871f33c2887ed8816173bb8a41779f82ecfdff7ff469260ec468ec5e60887575');
